[package]
name = "fairdeal-escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
soroban-sdk = "21.7.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[profile.release-with-logs]
inherits = "release"
debug = true
